name: Build

on:
  push:
    paths:
      - "bookmarker-api/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "bookmarker-api/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Fix permissions for Maven Wrapper
        run: chmod +x ./bookmarker-api/mvnw

      - name: Build with Maven
        run: ./bookmarker-api/mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          cd bookmarker-api
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmarker-api .
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
